module.exports = {
  siteMetadata: {
    title: 'Codepunkt',
    description:
      'Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.',
    author: '@code_punkt',
  },
  plugins: [
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'blog',
        path: `${__dirname}/src/pages/blog`,
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'images',
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: 'gatsby-plugin-mdx',
      options: {
        extensions: ['.mdx'],
        defaultLayouts: {
          default: require.resolve('./src/templates/blog-post.js'),
        },
        rehypePlugins: [
          // adds id attributes to headings
          require('rehype-slug'),
          // adds links pointing to the heading ids generated by
          // rehype-slug
          require('rehype-autolink-headings'),
        ],
        gatsbyRemarkPlugins: [
          // copies referenced files relative to mdx files to the
          // public folder and adjusts the references accordingly
          { resolve: 'gatsby-remark-copy-linked-files' },
          // converts single and double straight quotes to curly
          // ones, converts three dots to ellipses and double dashes
          // to an em-dash
          {
            resolve: 'gatsby-remark-smartypants',
            options: { backticks: false },
          },
          // add target _blank to external links to open them in
          // a new page, add additional content for screen-readers
          // that warns before opening a new window and defines rel
          // attributes for external links
          {
            resolve: 'gatsby-remark-external-links',
            options: {
              target: '_blank',
              content: [
                {
                  type: 'element',
                  tagName: 'span',
                  properties: {
                    className: ['foo'],
                  },
                  children: [
                    {
                      type: 'text',
                      value: '(opens in a new window)',
                    },
                  ],
                },
              ],
            },
          },
        ],
      },
    },
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-catch-links',
    'gatsby-plugin-sharp',
    'gatsby-transformer-sharp',
    'gatsby-plugin-emotion',
    {
      resolve: 'gatsby-plugin-typography',
      options: {
        pathToConfigModule: 'src/style/typography',
        omitGoogleFont: true,
      },
    },
    {
      resolve: 'gatsby-plugin-manifest',
      options: {
        name: 'Codepunkt',
        short_name: 'Codepunkt',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/images/gatsby-icon.png',
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // 'gatsby-plugin-offline',
  ],
}
